services:
    app:
        env_file:
            - path: ./.env
              required: true
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        restart: always
        depends_on:
            - db
    db:
        container_name: db
        image: postgres:12
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgresD
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
